### ISSUE TITLE
class W3DEnvironment

### ISSUE THREAD

**Issue by hovi** [iv4xr-project/aplib#15]
This class seems like class that has basic prepared functionality for environments in 3D world.
It provides methods like:
* `observe`
* `interact`
* `moveToward`
* `loadWorld`

Are these supposed to be used by any client extending this class?
They are not very generic and don't really match our use-case. We basically have our own implementations for all of this.
* Method `observe` can work.
* Method `loadWorld` could, be we need id of the world (scenario to load). Either as method parameter or a variable in the class.
* Method `moveToward` could work, not sure in this, as I don't understand framework enough.¨
* Method `interact` is hard to use for us.

If these are really supposed to be generic, interface should be more generic and nicer. I imagine, that with some nice and generic methods, some goals and tactics could be implemented as part of aplib itself and then can work on any environment automatically (like some basic movements, actions). Is that the idea? If so, we can try to match the interface if possible.

Method `sendCommand_` suggests we use some kind of protocol with `EnvOperation` variable to communicate with the game.
I see it as problem for another layer and this class is not really supposed to know about implementation of communication to this detail.
In our case for example, we communicate very differently and we just kept this method empty.

**Comment by wooshrow** [comment]
Hi, let me first address the `sendCommand_` and `EnvOperation` question. These derive all the way from the root-class `Environment`. The mechanism was initially intended to allow instrumenters to be hooked to an Environment, as the Environment keeps track of the last EnvOperation it sent. But admittedly this functionality is perhaps not always needed.

A simpler approach would indeed to just override sendCommand()  (and accepting you'll lose that instrumenters-feature)

As for the APIs for W3DEnvironment (observe, loadWorld, etc) ... do you have suggestions for a better interface? (we should come up with something more speciifc than just sendCommand() I suppose) How do you think of this:

- loadWorld(String ... arg) // allowing you to pass a series of configuration parameters
- observe(String agentId)
- moveToward(String agentId, Vec3 direction) // and where the length of this vector is interpreted as speed, what that is relevant for the target system, and else ignored (if the system just use some pre-defined speed).
- interact(String agentId, String targetId, String interactionType) // I thought this is very generic. It allows you to target any entity as long as it has an id, with whatever type of interaction, as long it is identifiable by some string, no?

**Comment by wooshrow** [comment]
I will look at "Interface" scheme (so you implement a Java interface) rather than extending this W3DEnv. This interface can be more general to accomodate yours as well as existing W3DEnv
